/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Cover from "../images/about_cover.jpg"

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.header__container}>
          <div className={styles.header__image}>
          <Image src={Cover} alt="cover" objectFit="cover" />
          {/* <Image src={Cover} alt="cover" layout="responsive" objectFit="contain" /> */}
          </div>
        <div className={styles.header__contents}>
          <h2>About Us</h2>
          <p>We're centered on what's best for you and your business</p>
          <p>We strive to be a partner to businesses big and small, providing the professional prowess you need to chart your path forward. It’s all part of our mission: To deliver an unmatched experience you won’t get anywhere else.</p>
        </div>
        </section>
      </main>
    </div>
  )
}
